[project]
name = "toronto-bike-traffic-api"
version = "0.1.0"
description = "Toronto Bike Traffic API"
requires-python = ">=3.9"
dependencies = [
    "Flask==3.1.2",
    "flask-cors==6.0.1",
    "python-dotenv==1.2.1",
    "pandas==2.3.3",
]

[project.scripts]
app = "app_vercel:app"